[package]
name = "arithmetic-of-letters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fontdue = "0.7.3"
pest = "2.7.0"
tiny-skia = "0.11.1"
